### ISSUE TITLE
panes (tmuxinator) doesn't works

### ISSUE THREAD

**Issue by dianapinkberry** [snare/voltron#144]
Hi. I configure `voltron.yml` file with your example, and panes doesn't works.
Here is my `voltron.yml `
```
# ~/.tmuxinator/voltron.yml
name: voltron
root: ~/
windows:
  # two spaces
  - madhax:
      # four spaces
      layout: 15a8,169x41,0,0{147x41,0,0[147x13,0,0{81x13,0,0,60,65x13,82,0,61},147x19,0,14,62,147x7,0,34{89x7,0,34,63,57x7,90,34,64}],21x41,148,0,65}
      panes:
        # two spaces
        - voltron view disasm
        - voltron view bp
        - lldb
        - voltron view stack
        - voltron view bt
        - voltron view reg
```

That's what i have
<img width="1170" alt="2016-04-27 11 44 19" src="https://cloud.githubusercontent.com/assets/17407456/14846787/9a3904a4-0c76-11e6-920e-0f2e5c64e6dd.png">
