### ISSUE TITLE
Voltron causing gdb to crash when views launched with tmuxp/tmuxinator/screen

### ISSUE THREAD

**Issue by bitshiftnetau** [snare/voltron#264]
System: Arch Linux 
Kernel: 4.19.91-1-lts
Debugger: arm-none-eabi-gdb

openocd.cfg:

```
source [find /usr/share/openocd/scripts/interface/jlink.cfg]

jlink serial XXXXXXXXX

transport select swd
adapter_khz 1000

set CHIPNAME efm32

gdb_flash_program enable
gdb_memory_map enable
gdb_report_data_abort enable

source [find /usr/share/openocd/scripts/target/efm32.cfg]

```

 
.gdbinit:

```
target remote localhost:3333
monitor reset halt
monitor resume
load /srv/code/c/spongecake/build/release/spongecake.axf
symbol-file /srv/code/c/spongecake/build/release/spongecake.axf
source /usr/lib/python3.8/site-packages/voltron/entry.py

```

.tmuxp.yaml:
```
session_name: 4-pane-split
windows:
- window_name: dev window
  layout: tiled
  shell_command_before:
    - cd ~/                    # run as a first command in all panes
  panes:
      - arm-none-eabi-gdb --command=/srv/code/c/spongecake/tools/gdb/.gdbinit
      - voltron view disasm
      - voltron view reg
      - voltron view stack
      - voltron view bp
```

If I run:

`tmux load .`

It loads up the panes, then drops a connection error (because voltron isn't loaded yet), then gdb sources the entry point for voltron and then does one of a two things:

- connects and displays a view
- seg faults

What's very strange, is that I can't reliably reproduce this fault by eliminating certain views with one exception: when it is one pane with gdb and one pane with voltron. Other than that, it randomly segfaults with 2 or all of the views and also randomly works with 1 or all of the views. I know this has to be a voltron+screen(or tmux)+gdb issue because opening voltron views in independent terminals works just fine, no problems at all but adding that muxer breaks everything. 

Same issue with either tmuxinator, tmuxp, or screen.

RAM is also not even close to being full and virtual memory has been expanded to 'infinite'. 

Any suggestions?
